# -*- coding: utf-8 -*-
"""ficha de contacto-0.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTEpxTsrjC4k230U5aqWKGNdEL4G33of
"""

contacto = [] #ejercicio-ficha



























while True:
  nuevo_contacto = {}
  nuevo_contacto["nombre"] = input("nombre:")
  nuevo_contacto["telefono"] = input("telefono:")
  nuevo_contacto["email"] = input("email:")
  nuevo_contacto["edad"] = int(input("edad:"))

  contacto.append(nuevo_contacto)


  continuar = input("¿Desea agregar otro contacto? (s/n): ").lower()
  if continuar != 's':
    break


print("ficha de contacto:")
print(contacto)


editar = input("editar (s/n):").upper()

if editar == "S":

  if contacto:
    contact_index_to_edit = 0

    area = input("que area desea editar:(nombre/telefono,email,edad):").lower()
    nuevo_valor  = input("nuevo valor:")

    if area == "edad":
      try:

        contacto[contact_index_to_edit][area] = int(nuevo_valor)
      except ValueError:
        print("Error: La edad debe ser un número entero.")
    elif area in ["nombre", "telefono", "email"]:
      contacto[contact_index_to_edit][area] = nuevo_valor
    else:
      print("Área inválida para editar.")
  else:
    print("No hay contactos para editar.")


print("ficha actualizada:")
print(contacto)